// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rdist_earth_cpp
arma::mat rdist_earth_cpp(NumericMatrix x1, NumericMatrix x2, bool miles);
RcppExport SEXP fooR_rdist_earth_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP milesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< bool >::type miles(milesSEXP);
    __result = Rcpp::wrap(rdist_earth_cpp(x1, x2, miles));
    return __result;
END_RCPP
}
