# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Great circle distance matrix.
#'
#' Given a set of longitude/latitude locations, \code{rdist_earth_cpp}
#' computes the Great circle (geographic) distance matrix among all pairings.
#'
#' Surprisingly this is all done efficiently in R by dot products of the
#' direction cosines.  This function is a (partial!) port to C++ of D. Nychka's
#' \code{rdist.earth} function from the fields R package.
#'
#' @param x Matrix of first set of lon/lat coordinates; first column is
#' the longitudes and the second is the latitudes.
#' @params miles If true, distances are in statute miles. If false, distances
#' are in kilometers.
#' @params R Radius to use for sphere to find spherical distances. If NULL,
#' the radius is either in miles or km depending on the values of the miles
#' argument. If R = 1, then distances are of course in radians.
rdist_earth_cpp <- function(x1, x2, miles = TRUE) {
    .Call('fooR_rdist_earth_cpp', PACKAGE = 'fooR', x1, x2, miles)
}

